### PR TITLE
seperate reader from plugin

### PR DESCRIPTION
**Pull request by 0b1kn00b**
Would I be barking up the wrong tree with this?

### CODE REVIEW

**Comment by back2dos** [comment]
I can see why this would be nice, but struggle to see a benefit that would outweigh a (breaking) change in the public API. Would you care to enlighten me? ^^

**Comment by 0b1kn00b** [comment]
It makes the thing a general way of building types. 
You don't necessarily parse a file on 'onTypeNotFound', and with the macro-in-macro restrictions you've effectively got either macro calls, or build directives but not both afaik.
So `Generic<T>` where you can inspect `T` and generate

**Comment by 0b1kn00b** [comment]
Darn sausage fingers. Am I off base? Isn't it possible that extensions might require some coordination?

**Comment by 0b1kn00b** [comment]
I can imagine a non-breaking variant with Abstracts

**Comment by 0b1kn00b** [comment]
`SyntaxHub.classLevel.add` is probably what I was looking for. ^_^

**Comment by back2dos** [comment]
The "frontends" are really meant for plugging in source file -> type providers. Then there are class/expression level transforms. And if you want something that helps with `@:genericBuild` then `tink.macro.BuildCache` is the way to go. But I still feel like I'm not quite getting your use case ^^

**Comment by 0b1kn00b** [comment]
Well, you know. It started off as a bug in my dependency injector, so now I'm doing an exploration as to what the what.

**Pull request closed without merging**
